# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    default_db_server_version: '11.4.9-MariaDB'
    app.google.contacts_import_limit: '%env(int:default:default_google_contacts_import_limit:GOOGLE_CONTACTS_IMPORT_LIMIT)%'
    default_google_contacts_import_limit: 70
    app.xml.import_limit: '%env(int:default:default_xml_import_limit:XML_IMPORT_LIMIT)%'
    default_xml_import_limit: 70

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $importLimit: '%app.google.contacts_import_limit%'

    App\Service\ContactImport\XmlImportService:
        arguments:
            $importLimit: '%app.xml.import_limit%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    _instanceof:
        App\Service\ContactImport\ContactDuplicateCheckerInterface:
            tags: ['app.contact_duplicate_checker']

    App\EventSubscriber\AuditLogSubscriber:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
