services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      DB_CONNECTION: "${DB_CONNECTION:-sqlite}"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_USER: "${MARIADB_USER:-app}"
      DB_PASSWORD: "${MARIADB_PASSWORD:-!ChangeMe!}"
      DB_NAME: "${MARIADB_DB:-app}"
      DB_VERSION: "11.4.9-MariaDB"
      MAILER_DSN: "smtp://mailpit:1025"

  database:
    profiles: [ "mysql" ]
    image: mariadb:${MARIADB_VERSION:-11.4}
    environment:
      MARIADB_DATABASE: ${MARIADB_DB:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost -u${MARIADB_USER:-app} -p${MARIADB_PASSWORD:-!ChangeMe!} || exit 1" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  database_data:
