#!/bin/sh
set -e

# Navigate to core directory for commands
cd /app/core

# 0. Secret Generation (Auto-generate if missing)
# This allows running on NAS/Docker Hub without manual setup
# We store in var/ because it is likely to be persisted via volume
mkdir -p var
SECRET_FILE="var/secrets.env"

# Function to generate a random secret
generate_secret() {
    openssl rand -hex 32
}

# Check APP_SECRET
if [ -z "$APP_SECRET" ]; then
    echo "APP_SECRET not set. Checking $SECRET_FILE..."
    if [ -f "$SECRET_FILE" ] && grep -q "APP_SECRET=" "$SECRET_FILE"; then
        export APP_SECRET=$(grep "APP_SECRET=" "$SECRET_FILE" | cut -d '=' -f2)
        echo "Loaded APP_SECRET from $SECRET_FILE"
    else
        echo "Generating new APP_SECRET..."
        export APP_SECRET=$(generate_secret)
        echo "APP_SECRET=$APP_SECRET" >> "$SECRET_FILE"
    fi
fi

# Check JWT_PASSPHRASE
if [ -z "$JWT_PASSPHRASE" ]; then
    echo "JWT_PASSPHRASE not set. Checking $SECRET_FILE..."
    if [ -f "$SECRET_FILE" ] && grep -q "JWT_PASSPHRASE=" "$SECRET_FILE"; then
        export JWT_PASSPHRASE=$(grep "JWT_PASSPHRASE=" "$SECRET_FILE" | cut -d '=' -f2)
        echo "Loaded JWT_PASSPHRASE from $SECRET_FILE"
    else
        echo "Generating new JWT_PASSPHRASE..."
        export JWT_PASSPHRASE=$(generate_secret)
        echo "JWT_PASSPHRASE=$JWT_PASSPHRASE" >> "$SECRET_FILE"
    fi
fi

# Ensure secrets are available to subsequent commands
export APP_SECRET
export JWT_PASSPHRASE

# Configure Database Connection
if [ -z "$DATABASE_URL" ]; then
    DB_CONNECTION=${DB_CONNECTION:-sqlite}
    
    if [ "$DB_CONNECTION" = "mysql" ]; then
        echo "Configuring for MySQL/MariaDB..."
        # Default mysql port
        DB_PORT=${DB_PORT:-3306}
        # Construct DATABASE_URL for MySQL
        export DATABASE_URL="mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=${DB_VERSION}&charset=utf8mb4"
    else
        echo "Configuring for SQLite..."
        # Create data directory if it doesn't exist
        mkdir -p var
        touch var/data.db
        chmod 666 var/data.db
        # Construct DATABASE_URL for SQLite
        export DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
    fi
    
    # Write to .env.local so CLI commands (docker exec) can pick it up
    echo "DATABASE_URL=\"$DATABASE_URL\"" > .env.local
fi


# Generate JWT keys if they don't exist
if [ ! -f config/jwt/private.pem ]; then
    echo "Generating JWT keys..."
    mkdir -p config/jwt
    php bin/console lexik:jwt:generate-keypair --skip-if-exists --no-interaction
fi

# Always fix permissions (in case they were generated by root or mounted incorrectly)
echo "Fixing JWT key permissions..."
chown -R www-data:www-data config/jwt
chmod 640 config/jwt/private.pem
chmod 644 config/jwt/public.pem

# Run migrations
# Run migrations or schema update
if [ "${DB_CONNECTION}" = "sqlite" ]; then
    echo "Updating schema for SQLite..."
    php bin/console doctrine:schema:update --force --complete
else
    echo "Running database migrations..."
    max_retries=20
    count=0
    until php bin/console doctrine:migrations:migrate --no-interaction || [ $count -eq $max_retries ]; do
        echo "Waiting for database to be ready (attempt $((count + 1))/$max_retries)..."
        sleep 3
        count=$((count + 1))
    done
fi

# Clear cache for production
php bin/console cache:clear --no-interaction

# Start messenger consumer in background
echo "Starting messenger worker..."
# Using a loop to ensure it restarts if it crashes (simple supervision)
(while true; do php bin/console messenger:consume async --memory-limit=128M --time-limit=3600; sleep 5; done) &

# Start cron daemon in background
echo "Starting crond..."
crond -b

# Go back to app root for the main command
cd /app

exec "$@"
