#!/bin/sh
set -e

# Navigate to core directory for commands
cd /app/core

# Generate JWT keys if they don't exist
if [ ! -f config/jwt/private.pem ]; then
    echo "Generating JWT keys..."
    mkdir -p config/jwt
    php bin/console lexik:jwt:generate-keypair --skip-if-exists
fi

# Always fix permissions (in case they were generated by root or mounted incorrectly)
echo "Fixing JWT key permissions..."
chown -R www-data:www-data config/jwt
chmod 640 config/jwt/private.pem
chmod 644 config/jwt/public.pem

# Run migrations
echo "Running database migrations..."
max_retries=20
count=0
until php bin/console doctrine:migrations:migrate --no-interaction || [ $count -eq $max_retries ]; do
    echo "Waiting for database to be ready (attempt $((count + 1))/$max_retries)..."
    sleep 3
    count=$((count + 1))
done

# Clear cache for production
php bin/console cache:clear --no-interaction

# Start cron daemon in background
echo "Starting crond..."
crond -b

# Go back to app root for the main command
cd /app

exec "$@"
