/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit_logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of AuditLog resources.
         * @description Retrieves the collection of AuditLog resources.
         */
        get: operations["api_audit_logs_get_collection"];
        put?: never;
        /**
         * Creates a AuditLog resource.
         * @description Creates a AuditLog resource.
         */
        post: operations["api_audit_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit_logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a AuditLog resource.
         * @description Retrieves a AuditLog resource.
         */
        get: operations["api_audit_logs_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the AuditLog resource.
         * @description Removes the AuditLog resource.
         */
        delete: operations["api_audit_logs_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the AuditLog resource.
         * @description Updates the AuditLog resource.
         */
        patch: operations["api_audit_logs_id_patch"];
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Contact resources.
         * @description Retrieves the collection of Contact resources.
         */
        get: operations["api_contacts_get_collection"];
        put?: never;
        /**
         * Creates a Contact resource.
         * @description Creates a Contact resource.
         */
        post: operations["api_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Contact resource.
         * @description Retrieves a Contact resource.
         */
        get: operations["api_contacts_id_get"];
        /**
         * Replaces the Contact resource.
         * @description Replaces the Contact resource.
         */
        put: operations["api_contacts_id_put"];
        post?: never;
        /**
         * Removes the Contact resource.
         * @description Removes the Contact resource.
         */
        delete: operations["api_contacts_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Contact resource.
         * @description Updates the Contact resource.
         */
        patch: operations["api_contacts_id_patch"];
        trace?: never;
    };
    "/api/contact_dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ContactDate resources.
         * @description Retrieves the collection of ContactDate resources.
         */
        get: operations["api_contact_dates_get_collection"];
        put?: never;
        /**
         * Creates a ContactDate resource.
         * @description Creates a ContactDate resource.
         */
        post: operations["api_contact_dates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact_dates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ContactDate resource.
         * @description Retrieves a ContactDate resource.
         */
        get: operations["api_contact_dates_id_get"];
        /**
         * Replaces the ContactDate resource.
         * @description Replaces the ContactDate resource.
         */
        put: operations["api_contact_dates_id_put"];
        post?: never;
        /**
         * Removes the ContactDate resource.
         * @description Removes the ContactDate resource.
         */
        delete: operations["api_contact_dates_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the ContactDate resource.
         * @description Updates the ContactDate resource.
         */
        patch: operations["api_contact_dates_id_patch"];
        trace?: never;
    };
    "/api/contact_names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ContactName resources.
         * @description Retrieves the collection of ContactName resources.
         */
        get: operations["api_contact_names_get_collection"];
        put?: never;
        /**
         * Creates a ContactName resource.
         * @description Creates a ContactName resource.
         */
        post: operations["api_contact_names_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact_names/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ContactName resource.
         * @description Retrieves a ContactName resource.
         */
        get: operations["api_contact_names_id_get"];
        /**
         * Replaces the ContactName resource.
         * @description Replaces the ContactName resource.
         */
        put: operations["api_contact_names_id_put"];
        post?: never;
        /**
         * Removes the ContactName resource.
         * @description Removes the ContactName resource.
         */
        delete: operations["api_contact_names_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the ContactName resource.
         * @description Updates the ContactName resource.
         */
        patch: operations["api_contact_names_id_patch"];
        trace?: never;
    };
    "/api/contacts/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ContactTimeline resource.
         * @description Retrieves a ContactTimeline resource.
         */
        get: operations["get_contact_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a user token.
         * @description Creates a user token.
         */
        post: operations["login_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a User resource.
         * @description Creates a User resource.
         */
        post: operations["api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a User resource.
         * @description Retrieves a User resource.
         */
        get: operations["api_users_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditLog: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string;
            entityType?: string;
            entityId?: number | null;
            action?: string;
            changes?: {
                [key: string]: string | null;
            } | null;
            snapshotBefore?: {
                [key: string]: string | null;
            } | null;
            snapshotAfter?: {
                [key: string]: string | null;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            tenant?: string;
        };
        "AuditLog-audit.read": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string;
            entityType?: string;
            entityId?: number | null;
            action?: string;
            changes?: {
                [key: string]: string | null;
            } | null;
            snapshotBefore?: {
                [key: string]: string | null;
            } | null;
            snapshotAfter?: {
                [key: string]: string | null;
            } | null;
            /** Format: date-time */
            createdAt?: string;
        };
        "AuditLog.jsonMergePatch": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string;
            entityType?: string;
            entityId?: number | null;
            action?: string;
            changes?: {
                [key: string]: string | null;
            } | null;
            snapshotBefore?: {
                [key: string]: string | null;
            } | null;
            snapshotAfter?: {
                [key: string]: string | null;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            tenant?: string;
        };
        "AuditLog.jsonld-audit.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string;
            entityType?: string;
            entityId?: number | null;
            action?: string;
            changes?: {
                [key: string]: string | null;
            } | null;
            snapshotBefore?: {
                [key: string]: string | null;
            } | null;
            snapshotAfter?: {
                [key: string]: string | null;
            } | null;
            /** Format: date-time */
            createdAt?: string;
        };
        Collection: {
            /** @description Checks whether the collection is empty (contains no elements). */
            readonly empty?: boolean;
            /** @description Gets all keys/indices of the collection. */
            readonly keys?: number[] | string[];
            /** @description Gets all values of the collection. */
            readonly values?: (string | null)[];
            readonly iterator?: unknown;
        };
        "Collection.jsonld": {
            /** @description Checks whether the collection is empty (contains no elements). */
            readonly empty?: boolean;
            /** @description Gets all keys/indices of the collection. */
            readonly keys?: number[] | string[];
            /** @description Gets all values of the collection. */
            readonly values?: (string | null)[];
            readonly iterator?: unknown;
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath?: string;
                /** @description The message associated with the violation */
                message?: string;
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath?: string;
                /** @description The message associated with the violation */
                message?: string;
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        "Contact-contact.create": {
            contactNames?: components["schemas"]["ContactName-contact.create"][];
            contactDates?: components["schemas"]["ContactDate-contact.create"][];
        };
        "Contact-contact.create.jsonMergePatch": {
            contactNames?: components["schemas"]["ContactName-contact.create"][];
            contactDates?: components["schemas"]["ContactDate-contact.create"][];
        };
        "Contact-contact.read": {
            readonly id?: number;
            contactNames?: components["schemas"]["ContactName-contact.read"][];
            contactDates?: components["schemas"]["ContactDate-contact.read"][];
        };
        "Contact.jsonld-contact.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            contactNames?: components["schemas"]["ContactName.jsonld-contact.read"][];
            contactDates?: components["schemas"]["ContactDate.jsonld-contact.read"][];
        };
        "ContactDate-contact.create": {
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate-contact.read": {
            readonly id?: number;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate-contact_date.create_contact_date.update": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate-contact_date.create_contact_date.update.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate-contact_date.read": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate.jsonld-contact.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactDate.jsonld-contact_date.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
            /** Format: date-time */
            date?: string | null;
            text?: string | null;
        };
        "ContactName-contact.create": {
            family?: string | null;
            given?: string | null;
        };
        "ContactName-contact.read": {
            readonly id?: number;
            family?: string | null;
            given?: string | null;
        };
        "ContactName-contact_name.create_contact_name.update": {
            family?: string | null;
            given?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
        };
        "ContactName-contact_name.create_contact_name.update.jsonMergePatch": {
            family?: string | null;
            given?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
        };
        "ContactName-contact_name.read": {
            readonly id?: number;
            family?: string | null;
            given?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
        };
        "ContactName.jsonld-contact.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            family?: string | null;
            given?: string | null;
        };
        "ContactName.jsonld-contact_name.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            family?: string | null;
            given?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            contact?: string | null;
        };
        ContactTimeline: {
            id?: number;
            logs?: components["schemas"]["Collection"];
        };
        "ContactTimeline.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: number;
            logs?: components["schemas"]["Collection.jsonld"];
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        "User-user.create": {
            uuid?: string;
            plainPassword?: string | null;
        };
        "User-user.read": {
            readonly id?: number;
            uuid?: string;
        };
        "User.jsonld-user.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            uuid?: string;
        };
        Token: {
            readonly token?: string;
        };
        Credentials: {
            /** @example test-uuid-1234 */
            username?: string;
            /** @example password */
            password?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_audit_logs_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                entityType?: string;
                "entityType[]"?: string[];
                entityId?: number;
                "entityId[]"?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AuditLog collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["AuditLog.jsonld-audit.read"][];
                    };
                    "application/json": components["schemas"]["AuditLog-audit.read"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_audit_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new AuditLog resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["AuditLog"];
                "application/json": components["schemas"]["AuditLog"];
            };
        };
        responses: {
            /** @description AuditLog resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["AuditLog.jsonld-audit.read"];
                    "application/json": components["schemas"]["AuditLog-audit.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_audit_logs_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AuditLog identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AuditLog resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["AuditLog.jsonld-audit.read"];
                    "application/json": components["schemas"]["AuditLog-audit.read"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_audit_logs_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AuditLog identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AuditLog resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_audit_logs_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AuditLog identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated AuditLog resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["AuditLog.jsonMergePatch"];
            };
        };
        responses: {
            /** @description AuditLog resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["AuditLog.jsonld-audit.read"];
                    "application/json": components["schemas"]["AuditLog-audit.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contacts_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Contact.jsonld-contact.read"][];
                    };
                    "application/json": components["schemas"]["Contact-contact.read"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Contact resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Contact-contact.create"];
                "application/json": components["schemas"]["Contact-contact.create"];
            };
        };
        responses: {
            /** @description Contact resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Contact.jsonld-contact.read"];
                    "application/json": components["schemas"]["Contact-contact.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contacts_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contact identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Contact.jsonld-contact.read"];
                    "application/json": components["schemas"]["Contact-contact.read"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contacts_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contact identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Contact resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Contact-contact.create"];
                "application/json": components["schemas"]["Contact-contact.create"];
            };
        };
        responses: {
            /** @description Contact resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Contact.jsonld-contact.read"];
                    "application/json": components["schemas"]["Contact-contact.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contacts_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contact identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contacts_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contact identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Contact resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Contact-contact.create.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Contact resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Contact.jsonld-contact.read"];
                    "application/json": components["schemas"]["Contact-contact.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_dates_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactDate collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ContactDate.jsonld-contact_date.read"][];
                    };
                    "application/json": components["schemas"]["ContactDate-contact_date.read"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_dates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new ContactDate resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ContactDate-contact_date.create_contact_date.update"];
                "application/json": components["schemas"]["ContactDate-contact_date.create_contact_date.update"];
            };
        };
        responses: {
            /** @description ContactDate resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactDate.jsonld-contact_date.read"];
                    "application/json": components["schemas"]["ContactDate-contact_date.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_dates_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactDate identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactDate resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactDate.jsonld-contact_date.read"];
                    "application/json": components["schemas"]["ContactDate-contact_date.read"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_dates_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactDate identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ContactDate resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ContactDate-contact_date.create_contact_date.update"];
                "application/json": components["schemas"]["ContactDate-contact_date.create_contact_date.update"];
            };
        };
        responses: {
            /** @description ContactDate resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactDate.jsonld-contact_date.read"];
                    "application/json": components["schemas"]["ContactDate-contact_date.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_dates_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactDate identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactDate resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_dates_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactDate identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ContactDate resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ContactDate-contact_date.create_contact_date.update.jsonMergePatch"];
            };
        };
        responses: {
            /** @description ContactDate resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactDate.jsonld-contact_date.read"];
                    "application/json": components["schemas"]["ContactDate-contact_date.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_names_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactName collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ContactName.jsonld-contact_name.read"][];
                    };
                    "application/json": components["schemas"]["ContactName-contact_name.read"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_names_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new ContactName resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ContactName-contact_name.create_contact_name.update"];
                "application/json": components["schemas"]["ContactName-contact_name.create_contact_name.update"];
            };
        };
        responses: {
            /** @description ContactName resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactName.jsonld-contact_name.read"];
                    "application/json": components["schemas"]["ContactName-contact_name.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_names_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactName identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactName resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactName.jsonld-contact_name.read"];
                    "application/json": components["schemas"]["ContactName-contact_name.read"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_names_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactName identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ContactName resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ContactName-contact_name.create_contact_name.update"];
                "application/json": components["schemas"]["ContactName-contact_name.create_contact_name.update"];
            };
        };
        responses: {
            /** @description ContactName resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactName.jsonld-contact_name.read"];
                    "application/json": components["schemas"]["ContactName-contact_name.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_contact_names_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactName identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactName resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_contact_names_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactName identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ContactName resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ContactName-contact_name.create_contact_name.update.jsonMergePatch"];
            };
        };
        responses: {
            /** @description ContactName resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactName.jsonld-contact_name.read"];
                    "application/json": components["schemas"]["ContactName-contact_name.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    get_contact_timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ContactTimeline identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ContactTimeline resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ContactTimeline.jsonld"];
                    "application/json": components["schemas"]["ContactTimeline"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The login data */
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        readonly token: string;
                    };
                };
            };
        };
    };
    api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new User resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["User-user.create"];
                "application/json": components["schemas"]["User-user.create"];
            };
        };
        responses: {
            /** @description User resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld-user.read"];
                    "application/json": components["schemas"]["User-user.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_users_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld-user.read"];
                    "application/json": components["schemas"]["User-user.read"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
