doctrine:
    dbal:
        url: '%app.database_url%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '%database_server_version%'


        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: false
        enable_native_lazy_objects: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        auto_mapping: true
        dql:
            datetime_functions:
                MONTH: Ari\Doctrine\DQL\Month
                DAY: Ari\Doctrine\DQL\Day
        mappings:
            Ari:
                type: attribute
                is_bundle: false
                dir: '%doctrine_entity_dir%'
                prefix: 'Ari\Entity'
                alias: Ari
        controller_resolver:
            auto_mapping: false
        filters:
            tenant:
                class: Ari\Doctrine\Filter\TenantFilter
                enabled: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            # dbname_suffix: '_test%test_token%'
            dbname_suffix: ''
        orm:
            dql:
                datetime_functions:
                    MONTH: Ari\Doctrine\DQL\Month
                    DAY: Ari\Doctrine\DQL\Day

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
