flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%storage_default_dir%'

        avatar.storage.local:
            adapter: 'local'
            options:
                directory: '%storage_avatars_dir%'

        avatar.storage.s3:
            adapter: 'aws'
            options:
                client: 'aws_s3.client'
                bucket: '%aws_s3_bucket%'
                prefix: 'avatars'

services:
    # We will alias avatar.storage based on environment manually in services.yaml or just handle it in the manager
    aws_s3.client:
        class: 'Aws\S3\S3Client'
        arguments:
            -
                endpoint: '%aws_s3_endpoint%'
                region: '%aws_s3_region%'
                version: 'latest'
                use_path_style_endpoint: true
                credentials:
                    key: '%aws_s3_key%'
                    secret: '%aws_s3_secret%'
