lexik_jwt_authentication:
    token_ttl: 300
    secret_key: '%jwt_secret_key%'
    public_key: '%jwt_public_key%'
    pass_phrase: '%jwt_passphrase%'
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: BEARER
